name: GitHub Pages

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Setup .NET
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # tag=v2

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release

      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet publish --configuration Release --output dist src/AdventOfCode.Web

      - name: Rewrite base href
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: SteveSandersonMS/ghaction-rewrite-base-href@5b54862a8831e012d4f1a8b2660894415fdde8ec # tag=v1
        with:
          html_path: dist/wwwroot/index.html
          base_href: /AdventOfCode/

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # tag=v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/wwwroot
          force_orphan: true
