name: GitHub Pages

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release

      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet publish --configuration Release --output dist src/AdventOfCode.Web

      - name: Rewrite base href
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: SteveSandersonMS/ghaction-rewrite-base-href@5b54862a8831e012d4f1a8b2660894415fdde8ec # tag=v1
        with:
          html_path: dist/wwwroot/index.html
          base_href: /AdventOfCode/

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/wwwroot
          force_orphan: true
