name: GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x'
      
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Test
        run: dotnet test --configuration Release
        
      - name: Publish
        run: dotnet publish --configuration Release --output dist AdventOfCode.2020.Web
        
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: dist/wwwroot/index.html
          base_href: /AdventOfCode/
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/wwwroot
          force_orphan: true